// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uupcjzjngecdqhegiant.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cGNqempuZ2VjZHFoZWdpYW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDQ2NTcsImV4cCI6MjA2Njc4MDY1N30.k84-ue8l7kld1orOG-TDX98t9hLlR-nXHn1uKeWIROA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});